// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';
import {
  assertDevelopmentDatabaseIsLocal,
  getEnvironmentFiles,
} from './src/config/environment';

config({ path: getEnvironmentFiles() });

const migrationUrl =
  process.env['DATABASE_DIRECT_URL'] ??
  process.env['DATABASE_URL']?.replace('-pooler.', '.');

assertDevelopmentDatabaseIsLocal(migrationUrl);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: migrationUrl,
  },
});
