
const USER_ROLES = {
    ADMIN: 'ADMIN',
    GUEST: 'GUEST',
    KITCHEN_STAFF: 'KITCHEN_STAFF',
    RESORT_STAFF: 'RESORT_STAFF',
    MAINTENANCE_STAFF: 'MAINTENANCE_STAFF',
} as const;

export default USER_ROLES;
