export const MAIN_VIRTUAL_TOUR_ID = 'main';

export const VIRTUAL_TOUR_TILE_COLUMNS = 8;
export const VIRTUAL_TOUR_TILE_ROWS = 4;
export const VIRTUAL_TOUR_PREVIEW_WIDTH = 1600;

export const VIRTUAL_TOUR_MAX_FILE_BYTES = 60 * 1024 * 1024;
export const VIRTUAL_TOUR_UPLOAD_FILE_COUNT =
  VIRTUAL_TOUR_TILE_COLUMNS * VIRTUAL_TOUR_TILE_ROWS + 1;

export const VIRTUAL_TOUR_CLOUDINARY_PREFIX = 'public/virtual-tour/scenes';
export const VIRTUAL_TOUR_UPLOAD_CONCURRENCY = 6;
