import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
    light: {
        background: '#ffffff',
        foreground: '#09090b',
        card: '#ffffff',
        cardForeground: '#09090b',
        popover: '#ffffff',
        popoverForeground: '#09090b',
        primary: '#4f46e5',
        primaryForeground: '#f5f3ff',
        secondary: '#f4f4f5',
        secondaryForeground: '#18181b',
        muted: '#f4f4f5',
        mutedForeground: '#71717a',
        accent: '#f4f4f5',
        accentForeground: '#18181b',
        destructive: '#ef4444',
        border: '#e4e4e7',
        input: '#e4e4e7',
        ring: '#a1a1aa',
        radius: '0.625rem',
    },
    dark: {
        background: '#09090b',
        foreground: '#fafafa',
        card: '#18181b',
        cardForeground: '#fafafa',
        popover: '#18181b',
        popoverForeground: '#fafafa',
        primary: '#4f46e5',
        primaryForeground: '#f5f3ff',
        secondary: '#27272a',
        secondaryForeground: '#fafafa',
        muted: '#27272a',
        mutedForeground: '#a1a1aa',
        accent: '#27272a',
        accentForeground: '#fafafa',
        destructive: '#f87171',
        border: 'rgba(255, 255, 255, 0.1)',
        input: 'rgba(255, 255, 255, 0.15)',
        ring: '#71717a',
        radius: '0.625rem',
    },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
    light: {
        ...DefaultTheme,
        colors: {
            background: THEME.light.background,
            border: THEME.light.border,
            card: THEME.light.card,
            notification: THEME.light.destructive,
            primary: THEME.light.primary,
            text: THEME.light.foreground,
        },
    },
    dark: {
        ...DarkTheme,
        colors: {
            background: THEME.dark.background,
            border: THEME.dark.border,
            card: THEME.dark.card,
            notification: THEME.dark.destructive,
            primary: THEME.dark.primary,
            text: THEME.dark.foreground,
        },
    },
};